// Generates src/styles/tokens.css from design/tokens.json.
// design/tokens.json is the source of truth (copied from the Design System artifact);
// never edit the generated CSS by hand — re-run `npm run tokens`.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const SRC = 'design/tokens.json';
const OUT = 'src/styles/tokens.css';
const t = JSON.parse(readFileSync(SRC, 'utf8'));

const [light, dark] = [t.color.themes[0].id, t.color.themes[1].id];
const declare = (pairs) => pairs.map(([k, v]) => `  --${k}: ${v};`).join('\n');

// ---- theme-independent tokens -------------------------------------------------
const shared = [];
for (const [k, v] of Object.entries(t.type.families)) shared.push([`font-${k}`, v]);
for (const g of t.type.groups) {
  for (const s of g.styles) {
    shared.push([`size-${s.name}`, s.fontSize]);
    shared.push([`lh-${s.name}`, String(s.lineHeight)]);
  }
}
for (const fam of ['spacing', 'radius', 'border']) {
  for (const tok of t[fam].tokens) shared.push([tok.name, tok.value]);
}

// ---- themed tokens ------------------------------------------------------------
const themed = (theme) => {
  const out = [];
  for (const tok of t.color.tokens) out.push([tok.name, tok.value[theme] ?? tok.value[light]]);
  for (const tok of t.shadow.tokens) {
    const value = tok.value[theme] ?? tok.value[light];
    out.push([tok.name, value]);
    // filter: drop-shadow() has no spread, so expose the colour on its own too
    out.push([`${tok.name}-color`, value.trim().split(/\s+/).pop()]);
  }
  return out;
};

const fonts = t.type.fonts
  .map(
    (f) => `@font-face {
  font-family: "${f.family}";
  src: url("/${f.file.replace(/^fonts\//, 'fonts/')}") format("woff2");
  font-weight: ${f.weight};
  font-style: normal;
  font-display: swap;
}`,
  )
  .join('\n');

const css = `/* GENERATED by scripts/tokens.mjs from design/tokens.json — do not edit. */

${fonts}

:root {
${declare(shared)}
${declare(themed(light))}
  color-scheme: light;
}

/* Explicit choice (set by the theme toggle / head script) */
:root[data-theme="${dark}"] {
${declare(themed(dark))}
  color-scheme: dark;
}

/* No-JS fallback: follow the OS unless the visitor picked a theme */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="${light}"]):not([data-theme="${dark}"]) {
${declare(themed(dark)).replace(/^ {2}/gm, '    ')}
    color-scheme: dark;
  }
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css);
console.log(`wrote ${OUT} (${css.length} bytes, ${t.color.tokens.length} colors)`);
